matrix:
  include:
    - language: go
      go:
        - "1.3"
        - "1.10"
        - "1.13"
        - master
      script:
        - make goTest
      after_success:
        - make goCoverage
        - bash < (curl -s https://codecov.io/bash) < -cF go
    
    - language: python
        python:
          - "2.7"
          - "3.4"
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.8-dev" 
          - "nightly"
        install:
          - make usersDependencies
        script:
          - make pythonTest
        after_success:
          - make pythonCoverage
          - bash < (curl -s https://codecov.io/bash) < -cF python