jobs:
  include:
    - stage: test
      name: "Go 1.3 tests"
      language: go
      go:
        - "1.3"
      script:
        - make goTest
      after_success:
        - make goCoverage
        - bash <(curl -s https://codecov.io/bash) -cF go
    - stage: test
      name: "Go 1.10 tests"
      language: go
      go:
        - "1.10"
      script:
        - make goTest
      after_success:
        - make goCoverage
        - bash <(curl -s https://codecov.io/bash) -cF go
    - stage: test
      name: "Go 1.13 tests"
      language: go
      go:
        - "1.13"
      script:
        - make goTest
      after_success:
        - make goCoverage
        - bash <(curl -s https://codecov.io/bash) -cF go
    - stage: test
      name: "Go master tests"
      language: go
      go:
        - master
      script:
        - make goTest
      after_success:
        - make goCoverage
        - bash <(curl -s https://codecov.io/bash) -cF go


    - stage: test
      name: "Python 3.4 tests"
      language: python
      python:
        - "3.4"
      install:
        - make usersDependencies
      script:
        - make pythonTest
      after_success:
          - make pythonCoverage
          - bash <(curl -s https://codecov.io/bash) -cF python
    - stage: test
      name: "Python 3.7 tests"
      language: python
      python:
        - "3.7"
      install:
        - make usersDependencies
      script:
        - make pythonTest
      after_success:
          - make pythonCoverage
          - bash <(curl -s https://codecov.io/bash) -cF python
    - stage: test
      name: "Python 3.8 tests"
      language: python
      python:
        - "3.8"
      install:
        - make usersDependencies
      script:
        - make pythonTest
      after_success:
          - make pythonCoverage
          - bash <(curl -s https://codecov.io/bash) -cF python
    - stage: test
      name: "Python 3.8-dev tests"
      language: python
      python:
        - "3.8-dev"
      install:
        - make usersDependencies
      script:
        - make pythonTest
      after_success:
          - make pythonCoverage
          - bash <(curl -s https://codecov.io/bash) -cF python
    - stage: test
      name: "Python nightly tests"
      language: python
      python: 
        - "nightly"
      install:
        - make usersDependencies
      script:
        - make pythonTest
      after_success:
          - make pythonCoverage
          - bash <(curl -s https://codecov.io/bash) -cF python