version: 2
jobs:
  build:
    docker: 
      - image: circleci/golang:1.13
    steps: 
      - checkout 
      - run: make goTest

  # build:
  #   docker:
  #     - image: circleci/python:3.7
  #   steps:
  #     - checkout
  #     - run: make pythonTest